Repository rocker-org/rocker-versioned2, pull requests merged in 2022-08, with the labels that each got.

#518 [Docs][CI] Change the link syntax on the wiki home from MediaWiki's one to Markdown's to reduce redering time on GitHub
  build/reports/wiki_home.Rmd
Labels: bug, documentation, CI

#523 [CI] More tests for rocker scripts
  .github/workflows/r-build-test.yml
Labels: enhancement, CI

#522 Remove libicu-le-hb0 and libicu4j-* from `rocker/r-ver`
  scripts/install_R_source.sh
Labels: enhancement, rocker scripts, pre-built images
