Repository rocker-org/rocker-versioned2, pull requests merged in 2022-12, with the labels that each got.

#574 Use the new base URL of Posit Public Package Manager
  NEWS.md
  README.md
  build/make-stacks.R
  dockerfiles/cuda11_4.1.0.Dockerfile
  dockerfiles/cuda11_4.1.1.Dockerfile
  dockerfiles/cuda11_4.1.2.Dockerfile
  dockerfiles/cuda11_4.1.3.Dockerfile
  dockerfiles/cuda11_4.2.0.Dockerfile
  dockerfiles/cuda11_4.2.1.Dockerfile
  dockerfiles/cuda_4.2.2.Dockerfile
  dockerfiles/r-ver_4.0.0.Dockerfile
  dockerfiles/r-ver_4.0.1.Dockerfile
  dockerfiles/r-ver_4.0.2.Dockerfile
  dockerfiles/r-ver_4.0.3.Dockerfile
  dockerfiles/r-ver_4.0.4.Dockerfile
  dockerfiles/r-ver_4.0.5.Dockerfile
  dockerfiles/r-ver_4.1.0.Dockerfile
  dockerfiles/r-ver_4.1.1.Dockerfile
  dockerfiles/r-ver_4.1.2.Dockerfile
  dockerfiles/r-ver_4.1.3.Dockerfile
  dockerfiles/r-ver_4.2.0.Dockerfile
  dockerfiles/r-ver_4.2.1.Dockerfile
  dockerfiles/r-ver_4.2.2.Dockerfile
  stacks/4.0.0.json
  stacks/4.0.1.json
  stacks/4.0.2.json
  stacks/4.0.3.json
  stacks/4.0.4.json
  stacks/4.0.5.json
  stacks/4.1.0.json
  stacks/4.1.1.json
  stacks/4.1.2.json
  stacks/4.1.3.json
  stacks/4.2.0.json
  stacks/4.2.1.json
  stacks/4.2.2.json
Labels: enhancement, CI, pre-built images

#575 Add lsb-release for shiny-server
  .github/workflows/r-build-test.yml
  scripts/install_shiny_server.sh
Labels: bug

#580 [CI] Update the reporte template to skip cuda images' notice message in package listing files
  build/reports/template.Rmd
Labels: bug, CI

#576 Remove installation of wgrib from geospatial builds
  scripts/install_geospatial.sh
Labels: rocker scripts, pre-built images

#578 Allow building `rocker/rstudio:latest-daily` on linux/arm64 platform with skipping install quarto CLI
  scripts/install_quarto.sh
Labels: enhancement, rocker scripts

#581 Move (rather than link) the wgrib2 executable and delete build dir
  scripts/install_wgrib2.sh
Labels: enhancement, rocker scripts, pre-built images

#583 [CI] Deinstalled apt packages should not be listed in reports
  .github/workflows/reports.yml
  Makefile
  build/reports/template.Rmd
Labels: CI

#584 [CI] Build the `linux/arm64` platform to `rocker/rstudio:latest-daily`
  .github/workflows/devel.yml
  bakefiles/core-latest-daily.docker-bake.json
  build/make-stacks.R
  stacks/core-latest-daily.json
Labels: CI, pre-built images

#587 [CI] Update for using purrr 1.0.0; Use `rlang::zap()` instead of `NULL`
  build/make-bakejson.R
Labels: CI
